name: Build and Publish

on:
  release:
    types: [ published ]

jobs:
  chart-path:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Print Release Payload
          run: echo '${{ toJson(github.event.release)}}'
        - name: Get Chart Path
          id: get-chart-path
          run: |
            chart_name=$(echo $GITHUB_REF_NAME| rev | cut -d'-' -f2- | rev)
            chart_path=$(find . -name Chart.yaml -exec sh -c "yq eval '.name' {} | grep -q '$chart_name' && echo \$(dirname {})" \;)
            echo "chart_path=$chart_path" >> "$GITHUB_OUTPUT"
    outputs:
        chart_path: ${{ steps.get-chart-path.outputs.chart_path }}