name: Dummy

on:
  workflow_run:
    workflows: [Test Var]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  job_one:
    runs-on: ubuntu-latest

    steps:
      - name: s1
        id: set-branch
        run: |
          echo "This is being auto-call"
          echo Hi
          echo ${{ github.head_ref }}
